# Generated by Django 5.2.4 on 2025-08-08 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_installedequipment_last_service_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installedequipment',
            options={'ordering': ['-date_installed', 'name'], 'verbose_name_plural': 'Installed Equipment'},
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('donation', 'Donation')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='installedequipment',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='installedequipment',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='installedequipment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='active', help_text='Current operational status of the equipment', max_length=20),
        ),
    ]
