# Generated by Django 5.2 on 2025-08-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_installedequipment_options_post_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedequipment',
            name='category',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('mechanical', 'Mechanical'), ('software', 'Software'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='installedequipment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('available', 'Available'), ('maintenance', 'In Maintenance'), ('retired', 'Decommissioned')], default='active', help_text='Current operational status of the equipment', max_length=20),
        ),
    ]
