# Generated by Django 5.2 on 2025-08-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
