# Generated by Django 5.2 on 2025-08-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedequipment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedequipment',
            name='category',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('mechanical', 'Mechanical'), ('software', 'Software'), ('radiology', 'radiology'), ('ICU', 'ICU'), ('Triage', 'Triage'), ('Physiotherapy', 'Physiotherapy'), ('HDU', 'HDU'), ('Laboratory', 'Laboratory'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
